# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :osx, '12.0'
inhibit_all_warnings!
use_frameworks!

target 'LBBug' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LBBug
  pod 'SnapKit'

end
